### PR TITLE
Fix: FE bugs

### LINKED ISSUE #619: Cancel button in custom processes is badly positioned
Screenshot from 2020-01-17 11-07-25

### PR DESCRIPTION
**Pull request by lciolecki**
- Resolves #619 
- OAuth2 infinite redirects

### CODE REVIEW

File: ui/client/common/SystemUtils.ts [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+  }
+
+  public getUserId = (): string => {
+    if (_.isEmpty(localStorage.getItem(userId))) {
+      localStorage.setItem(userId, uuid4())
+    }
+    return localStorage.getItem(userId)
+  }
+
+  public getAuthorizationHeader = (): string => AUTHORIZATION_HEADER_NAMESPACE
```
Comment (arkadius) [inline ui/client/common/SystemUtils.ts]: Why this is a method instead of some kind of static constant?

Comment (lciolecki) [reply ui/client/common/SystemUtils.ts]: Done.
