### PR TITLE
Fix side node details

### LINKED ISSUE #514: Details of process with grouped nodes are badly presented
Steps to reproduce:
- group some nodes on process
- click on empty space on process

Expected behaviour: should be visible nice nodes details lists
Current behaviour: are presented: each letter of nodes name in separate line (looks like some iterating over string instead of list of nodes)

Screenshot from 2019-12-13 10-23-47

### PR DESCRIPTION
**Pull request by PPiedel**
This resolves #514

### CODE REVIEW

File: ui/client/components/right-panel/SideNodeDetails.js [hunk 1]
```diff
@@ -11,23 +10,25 @@ class SideNodeDetails extends Component {
       if (_.isArray(val)) {
```
Comment (lciolecki) [inline ui/client/components/right-panel/SideNodeDetails.js]: What a beautiful ifhell :)

Comment (lciolecki) [reply ui/client/components/right-panel/SideNodeDetails.js]: I think need there some factory to creating FlatObjectEntry.  Alsow in render method you don't need else statement.
