### PR TITLE
Fix: error information about copy

### LINKED ISSUE #542: copy content of input fields behaviour and notifications
1. when you copy content of a input field in node details modal a notification in shown

image

2. when you do
- select all (^A) in input field
- type new value
- copy value (^A ^C)
 
warning is produced and the value is restet to initial

### PR DESCRIPTION
**Pull request by lciolecki**
This resolves #542

### CODE REVIEW

File: ui/client/containers/Visualization.js [hunk 1]
```diff
@@ -52,6 +52,9 @@ class Visualization extends React.Component {
     }
   }
 
+  allowBindCopyShortcut = () =>
+    this.props.allModalsClosed && _.isEmpty(this.props.selectionState) === false
```
Comment (jedrz) [inline ui/client/containers/Visualization.js]: Wouldn't `!_.isEmpty(this.props.selectionState)` be more readable?

Comment (lciolecki) [reply ui/client/containers/Visualization.js]: Hmm, in future we want to rewrite this to TS, after that probably we will not use lodash ;)
