### PR TITLE
Typed map fixes

### LINKED ISSUE #674: When using TypedMap Map methods are suggested but do not validate
TypedMap has inconsistent behaviour. When we suggest methods in UI we have methods like empty, containsKey etc. but they do not validate on backend.
`
Screenshot from 2020-02-11 09-25-23

### PR DESCRIPTION
**Pull request by arkadius**
fixes #674

### CODE REVIEW

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/MapLikePropertyTypeDeterminer.scala [hunk 1]
```diff
@@ -0,0 +1,28 @@
+package pl.touk.nussknacker.engine.api.typed
+
+import java.util
+
+import pl.touk.nussknacker.engine.api.typed.typing.{Typed, TypedClass, TypingResult, Unknown}
+
+object MapLikePropertyTypeDeterminer {
```
Comment (mproch) [inline engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/MapLikePropertyTypeDeterminer.scala:7]: I wonder, maybe it should be in spel package? It's currently used only in Typer as far as I see, and it's behaviour is heavily dependent on property accessors in spel?
We would be able to use Avro classes then?

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/MapLikePropertyTypeDeterminer.scala [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+  def mapLikePropertyType(typ: TypedClass): Option[TypingResult] = typ match {
```
Comment (mproch) [inline engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/MapLikePropertyTypeDeterminer.scala:9]: can you add some doc what this method should return? So that when we add another case like avro we know what to do? :)

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypedMap.scala [hunk 3]
```diff
@@ -1,3 +1,63 @@
 package pl.touk.nussknacker.engine.api.typed
 
-case class TypedMap(fields: Map[String, Any])
\ No newline at end of file
+import java.{util => ju}
+
+case class TypedMap(fields: Map[String, Any]) extends ju.AbstractMap[String, Any] { self =>
```
Comment (mproch) [inline engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypedMap.scala:5]: I wonder - maybe we should use some map directly? Or is it for backwards compatibility?

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala [hunk 4]
```diff
@@ -152,7 +152,7 @@ object typing {
           val fieldTypes = fields.map {
             case (k, v) => k -> fromInstance(v)
           }
-          TypedObjectTypingResult(fieldTypes, TypedClass(classOf[TypedMap], Nil))
+          TypedObjectTypingResult(fieldTypes)
```
Comment (mproch) [inline engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala:155]: Good catch :+1:

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/MapLikePropertyTypeDeterminer.scala (hunk 1 above)
Comment (arkadius) [reply engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/MapLikePropertyTypeDeterminer.scala:7]: Good point - moved to typer, it shouldn't cause problems with Avro classes

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/MapLikePropertyTypeDeterminer.scala (hunk 2 above)
Comment (arkadius) [reply engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/MapLikePropertyTypeDeterminer.scala:9]: Added

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypedMap.scala (hunk 3 above)
Comment (arkadius) [reply engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypedMap.scala]: Indeed it will be less magic if we keep java Map for fields. Also I think that will be better if we will have equals working correctly with other maps - because of this I've replaced case class with plain serializable class.

I've added apply method for backward compatibility, and written some notice in MigrationGuide in case if someone use pattern matching on TypedMap

**Comment by lciolecki** [comment]
@arkadius please update also Changelog ;)

File: docs/MigrationGuide.md [hunk 5]
```diff
@@ -49,6 +49,11 @@ val source = new KafkaAvroSourceFactory(schemaRegistryProvider, processObjectDep
 val avroFixedSourceFactory = FixedKafkaAvroSourceFactory[GenericData.Record](processObjectDependencies)
 ```
 
+## In version 0.1.2 (not released yet)
```
Comment (mproch) [inline docs/MigrationGuide.md:52]: Do we want it in 0.1.2? Maybe in 0.2.0? It's not so badly needed, and it's not fully backwards compatible...

File: engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/sinks.scala [hunk 6]
```diff
@@ -16,14 +16,10 @@ object sinks {
...
 
   case class GenericJsonSerialization(topic: String) extends SimpleSerializationSchema[Any](topic, element => {
-      val objToEncode = element match {
-        // TODO: would be safer if will be added expected type in Sink and during expression evaluation,
-        // would be performed conversion to it
-        case TypedMap(fields) => fields
-        case other => other
-      }
-      encoder.encode(objToEncode).spaces2
+    // TODO: would be safer if will be added expected type in Sink and during expression evaluation,
```
Comment (mproch) [inline engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/sinks.scala:19]: Is this comment still relevant?

File: docs/MigrationGuide.md [hunk 7]
```diff
@@ -49,6 +49,11 @@ val source = new KafkaAvroSourceFactory(schemaRegistryProvider, processObjectDep
...
+
+* [#954](https://github.com/TouK/nussknacker/pull/954) `TypedMap` is not a case class wrapping scala Map anymore. If you have
+ done some pattern matching on it, you should use `case typedMap: TypedMap => typedMap.typedMap.asScala` instead.
```
Comment (mproch) [inline docs/MigrationGuide.md:55]: typedMap.typedMap.asScala => typedMap.asScala?

File: docs/MigrationGuide.md (hunk 5 above)
Comment (arkadius) [reply docs/MigrationGuide.md:52]: IMO it is quite badly needed, because it is fix for two bugs:
- we suggest methods that can't be used
- we accept something in expressions and it blow up in runtime.
Compatibility is broken only on very advanced usages, when you extract scala map from `TypedMap` (i can add such extractor BTW but IMO it will mess a code a bit)

File: engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/sinks.scala (hunk 6 above)
Comment (arkadius) [reply engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/sinks.scala:19]: I think so - this sink still accept anything, nothing changed in this place
