### PR TITLE
Validate clashed names and improve table filters resizing

### LINKED ISSUE #150: GUI Firefox issues - process list filter
**Describe the bug**
On Firefox 69.0.1

image

**To Reproduce**
1. Run the demo

**Expected behavior**
image

### LINKED ISSUE #359: new process id validation should check clash with archieved process id

### LINKED ISSUE #367: hr splitter line in modal should be centered horizontally
It looks like this:
2019-11-14 14_37_04-Nussknacker

Should look like this:
2019-11-14 14_37_25-Nussknacker

### PR DESCRIPTION
**Pull request by PPiedel**
This fixes #359
This fixes #367
This fixes #150
Imrpove processes table filters resizing

### CODE REVIEW

File: ui/client/containers/TableSelect.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
+import React from "react"
```
Comment (lciolecki) [inline ui/client/containers/TableSelect.js]: I think this is wrong space (/client/containers/) for this component..

File: ui/client/containers/SubProcesses.js [hunk 2]
```diff
@@ -34,49 +34,18 @@ class SubProcesses extends BaseProcesses {
...
-            ) : null
-          }
+          <TableSelect defaultValue={this.state.selectedCategories}
+                       options={this.props.filterCategories}
+                       placeholder={"Select categories.."}
+                       onChange={this.onCategoryChange}
+                       isMulti={true}
+                       isSearchable={true}/>
+
+          <AddProcessButton loggedUser={this.props.loggedUser}
```
Comment (lciolecki) [inline ui/client/containers/SubProcesses.js]: All attributes in one line? :)

File: ui/client/containers/SearchFilter.js [hunk 3]
```diff
@@ -0,0 +1,23 @@
+import filterIcon from "../assets/img/search.svg"
```
Comment (lciolecki) [inline ui/client/containers/SearchFilter.js]: I think this is wrong space (/client/containers/) for SearchFilter component..

File: ui/client/containers/BaseProcesses.js [hunk 4]
```diff
@@ -123,13 +81,26 @@ class BaseProcesses extends PeriodicallyReloadingComponent {
...
+    this.loadClashedNames(defaultProcessesSearchParams, (data) => HttpService.fetchProcesses(data));
+    this.loadClashedNames(defaultSubProcessesSearchParams, (data) => HttpService.fetchProcesses(data));
+    this.loadClashedNames(defaultArchivedProcessesSearchParams, (data) => HttpService.fetchProcesses(data));
+    this.loadClashedNames({}, () => HttpService.fetchCustomProcesses())
+  }
+
+  loadClashedNames = (searchParams, fetch) => {
+    const query = _.pick(queryString.parse(window.location.search), this.searchItems || [])
+    const data = Object.assign(query, searchParams)
+    fetch(data).then(response => {
```
Comment (lciolecki) [inline ui/client/containers/BaseProcesses.js]: We don't use fetch because it doesn't  support our policy of auth headers (OAuth2 case). Please move this method to HttpService and use axios.

Comment (PPiedel) [reply ui/client/containers/BaseProcesses.js]: Fetch is actually a method passed as param of this function

Comment (lciolecki) [reply ui/client/containers/BaseProcesses.js]: Upps.. :) I have'nt seen it ;p

File: ui/client/containers/TableSelect.js (hunk 1 above)
Comment (PPiedel) [reply ui/client/containers/TableSelect.js]: Done

File: ui/client/containers/SearchFilter.js (hunk 3 above)
Comment (PPiedel) [reply ui/client/containers/SearchFilter.js]: Done

File: ui/client/containers/SubProcesses.js (hunk 2 above)
Comment (PPiedel) [reply ui/client/containers/SubProcesses.js]: Why? It excedds Intelij default max width line
