### PR TITLE
Fix: Bug with cancel running process with error

### LINKED ISSUE #729: Cancel button is disabled when process has "Process currently is not running" state
It causes that user can't clean this error after manual cancellation of process in Flink.

### PR DESCRIPTION
**Pull request by lciolecki**
This close #729

### CODE REVIEW

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleStateStatus.scala [hunk 1]
```diff
@@ -14,4 +14,5 @@ object SimpleStateStatus {
   val Canceled: StoppedStateStatus = StoppedStateStatus("CANCELED")
   val Failed: ErrorStateStatus = ErrorStateStatus("FAILED")
   val Error: ErrorStateStatus = ErrorStateStatus("ERROR")
+  val RunningError: ErrorStateStatus = ErrorStateStatus("RUNNING_ERROR")
```
Comment (arkadius) [inline engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleStateStatus.scala]: Maybe better name will be `RuninngWithError` or `RuninngWithWarning`? Because now it looks like it is problem during run like process was deployed but can't run.

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala [hunk 2]
```diff
@@ -37,7 +38,8 @@ object SimpleProcessStateDefinitionManager extends ProcessStateDefinitionManager
     SimpleStateStatus.DuringCancel -> "/assets/states/stopping-running-animated.svg",
     SimpleStateStatus.Failed -> "/assets/states/failed.svg",
     SimpleStateStatus.Finished -> "/assets/states/success.svg",
-    SimpleStateStatus.Error -> "/assets/states/error.svg"
+    SimpleStateStatus.Error -> "/assets/states/error.svg",
+    SimpleStateStatus.RunningError -> "/assets/states/error.svg"
```
Comment (arkadius) [inline engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala]: Maybe we should use other icon to show that at the end this process is running like `deploy-failed.svg` for now and we should ask our ui-designers to add some `deploy-warning.svg`?

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala [hunk 3]
```diff
@@ -51,7 +53,7 @@ object SimpleProcessStateDefinitionManager extends ProcessStateDefinitionManager
     SimpleStateStatus.DuringCancel -> "The process currently is being canceled.",
     SimpleStateStatus.Failed -> "There are some problems with checking state of process..",
     SimpleStateStatus.Finished -> "The process completed successfully.",
-    SimpleStateStatus.Error -> "There are some errors with process state. Please check if everything is okay with process!"
+    SimpleStateStatus.Error -> "There are some errors with process state. Please check if everything is okay with process!",
```
Comment (arkadius) [inline engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala]: You don't missed something here? Looks like you didn't handle `RunningError`

File: ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatus.scala [hunk 4]
```diff
@@ -78,36 +78,42 @@ object ProcessStatus {
   }
 
   def simpleErrorShouldRunning(deployedVersionId: Long, user: String, previousState: Option[ProcessState]): ProcessStatus = simpleError(
+    errorStatus = SimpleStateStatus.RunningError,
```
Comment (arkadius) [inline ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatus.scala]: Here process is not running

Comment (lciolecki) [reply ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatus.scala]: ProcessState is not running but ProcessAction is deployed, so.. We should treat as running state.

 I've tested it by:
- deploy process 
- cancel process in flink

Then message should be 'Process should be running' and we should can do Cancle and Deploy action.

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala (hunk 3 above)
Comment (lciolecki) [reply engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala]: I've added a missing tooltip and description.

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala (hunk 2 above)
Comment (lciolecki) [reply engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala]: You are right - I will wait for incons.

File: engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleStateStatus.scala (hunk 1 above)
Comment (lciolecki) [reply engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleStateStatus.scala]: I've changed it to RunningWithError.

File: ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatus.scala (hunk 4 above)
Comment (lciolecki) [reply ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatus.scala]: After consider I've added DeployedWithError status.
