### PR TITLE
disable find dialog in ace

### LINKED ISSUE #1022: Application hijacks Ctrl+F in parameter editor
**Describe the bug**
Can't use Ctrl+F to search for value on page because Nussknacker displays its own search window:
obraz

Firefox 77, latest demo

### PR DESCRIPTION
**Pull request by JulianWielga**
Resolved #1022

### CODE REVIEW

File: ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.js [hunk 1]
```diff
@@ -23,6 +23,12 @@ var inputExprIdCounter = 0
 const identifierRegexpsWithoutDot = [/[#a-z0-9-_]/]
 const identifierRegexpsIncludingDot = [/[#a-z0-9-_.]/]
 
+const findCommandDisable = {
```
Comment (lciolecki) [inline ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.js:26]: listOfDisabledCommands?
