### PR TITLE
Fix React warnings in properties modal

### LINKED ISSUE #571: Warnings in react console
https://staging.nussknacker.io/visualization/Test123?businessView=false,  in Properties modal:

- VM51 react.development.js:188 Warning: Each child in a list should have a unique "key" prop.
- Warning: Failed prop type: Invalid prop `value` of type `number` supplied to `LabeledInput`, expected `string`.
- Warning: Failed prop type: Invalid prop `value` of type `number` supplied to `Input`, expected `string`.

### PR DESCRIPTION
**Pull request by PPiedel**
This resolves #571

### CODE REVIEW

File: ui/client/components/graph/node-modal/editors/field/Input.js [hunk 1]
```diff
@@ -29,7 +28,10 @@ export const Input = (props) => {
 
 Input.propTypes = {
   isMarked: PropTypes.bool,
-  value: PropTypes.string,
+  value: PropTypes.oneOfType([
```
Comment (mproch) [inline ui/client/components/graph/node-modal/editors/field/Input.js]: I wonder if it's enough? E.g. when we happen to use boolean or sth?

Comment (PPiedel) [reply ui/client/components/graph/node-modal/editors/field/Input.js]: There is a separate component for boolean (Checkbox)

Comment (mproch) [reply ui/client/components/graph/node-modal/editors/field/Input.js]: true
