### PR TITLE
Handle safe navigation in SpEL

### LINKED ISSUE #440: Suggestions for SpEL do not work well with safe navigation operator
https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions-operator-safe-navigation - currently using it breaks suggestions

### PR DESCRIPTION
**Pull request by mproch**
fixes #440

### CODE REVIEW

File: ui/client/test/ExpressionSuggester-test.js [hunk 1]
```diff
@@ -338,6 +338,12 @@ describe("expression suggester", () => {
       expect(suggestions).toEqual([{methodName: "toUpperCase", refClazz: {refClazzName: "java.lang.String"}}])
     }).then(done)
   })
+
+  it("should support safe navigation", (done) => {
+    suggestionsFor("#input?.barB.bazC?.", {row: 0, column: "#input?.barB.bazC?.".length }).then(suggestions => {
```
Comment (arkadius) [inline ui/client/test/ExpressionSuggester-test.js]: You don't need to duplicate expression in second parameter anymore :)

Comment (mproch) [reply ui/client/test/ExpressionSuggester-test.js]: great, thanks :)
