### PR TITLE
[FIX] Validate generate data input, closes #1

### LINKED ISSUE #1: Validate amount of test data to generate in UI
Clicking on `Generate` button shows a form and it allows for request the amount of test data. But the number is not validated and when I provide `bla` or `1000000000000000000000000000000000` then any error message is not shown. File is generated and contains only one line:

```
The requested resource could not be found.
```

### PR DESCRIPTION
**Pull request by mproch**
Fixes #1

### CODE REVIEW

File: ui/client/components/modals/GenerateTestDataDialog.js [hunk 1]
```diff
@@ -22,14 +25,23 @@ class GenerateTestDataDialog extends React.Component {
...
+        okBtnConfig={{disabled: !allValid(validators, [this.state.testSampleSize])}}
         type={Dialogs.types.generateTestData}
       >
         <p>Generate test data</p>
-        <input autoFocus={true} className="add-comment-on-save" value={this.state.testSampleSize} onChange={(e) => { this.setState({testSampleSize: e.target.value}) } }/>
+        <input
+          autoFocus={true}
+          className="add-comment-on-save"
+          value={this.state.testSampleSize}
+          onChange={(e) => { this.setState({testSampleSize: e.target.value}) } }
```
Comment (lciolecki) [inline ui/client/components/modals/GenerateTestDataDialog.js:41]: This should be defined as method at GenerateTestDataDialog.

Comment (mproch) [reply ui/client/components/modals/GenerateTestDataDialog.js]: ok, done
